# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

window = tk.Tk()
window.geometry("1024x1024")
window.configure(bg="#cdbfaf")
window.title("Kiosk_Pinkberry")

canvas = tk.Canvas(
    window,
    bg = "#cdbfaf",
    width = 1024,
    height = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x=0, y=0)

canvas.create_text(
    0,
    0,
    anchor="nw",
    text="",
    fill="#f7b4b8",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    498,
    891,
    anchor="nw",
    text="",
    fill="#ea7f85",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    0,
    130,
    anchor="nw",
    text="",
    fill="#f3e6e6",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    513,
    192,
    anchor="nw",
    text="",
    fill="#ffffff",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    595,
    748,
    anchor="nw",
    text="",
    fill="#ffffff",
    font=("Default Font", 12 * -1)
)

window.resizable(False, False)
window.mainloop()
