# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

window = tk.Tk()
window.geometry("1024x1024")
window.configure(bg="#000000")
window.title("Kiosk_Pinkberry")

canvas = tk.Canvas(
    window,
    bg = "#000000",
    width = 1024,
    height = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x=0, y=0)

canvas.create_text(
    0,
    0,
    anchor="nw",
    text="",
    fill="#ea7f85",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    108,
    126,
    anchor="nw",
    text="",
    fill="#f7b4b8",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    514,
    51,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    183,
    348,
    anchor="nw",
    text="THANK YOU FOR BUYING!",
    fill="#ffffff",
    font=("Kanit", 78 * -1)
)

canvas.create_text(
    334,
    643,
    anchor="nw",
    text="ORDER#24",
    fill="#ffffff",
    font=("Kanit", 40 * -1)
)

window.resizable(False, False)
window.mainloop()
