# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

window = tk.Tk()
window.geometry("1024x1024")
window.configure(bg="#cdbfaf")
window.title("Kiosk_Pinkberry")

canvas = tk.Canvas(
    window,
    bg = "#cdbfaf",
    width = 1024,
    height = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x=0, y=0)

canvas.create_text(
    0,
    0,
    anchor="nw",
    text="",
    fill="#f7b4b8",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    0,
    144,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    33,
    630,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    289,
    630,
    anchor="nw",
    text="",
    fill="#766262",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    544,
    630,
    anchor="nw",
    text="",
    fill="#766262",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    544,
    630,
    anchor="nw",
    text="",
    fill="#766262",
    font=("Default Font", 12 * -1)
)

image_5 = tk.PhotoImage(file=load_asset("None"))

canvas.create_image(623, 862, image=image_5)

canvas.create_text(
    790,
    630,
    anchor="nw",
    text="",
    fill="#766262",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    33,
    888,
    anchor="nw",
    text="",
    fill="#766262",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    289,
    888,
    anchor="nw",
    text="",
    fill="#766262",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    544,
    888,
    anchor="nw",
    text="",
    fill="#766262",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    790,
    888,
    anchor="nw",
    text="",
    fill="#766262",
    font=("Default Font", 12 * -1)
)

window.resizable(False, False)
window.mainloop()
