# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

window = tk.Tk()
window.geometry("1024x1024")
window.configure(bg="#f3e6e6")
window.title("Kiosk_Pinkberry")

canvas = tk.Canvas(
    window,
    bg = "#f3e6e6",
    width = 1024,
    height = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x=0, y=0)

canvas.create_text(
    0,
    0,
    anchor="nw",
    text="",
    fill="#f7b4b8",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    43,
    273,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    549,
    278,
    anchor="nw",
    text="$5.55",
    fill="#000000",
    font=("Kanit", 50 * -1)
)

canvas.create_text(
    56,
    920,
    anchor="nw",
    text="INGREDIENTS: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ",
    fill="#000000",
    font=("Kanit", 26 * -1)
)

canvas.create_text(
    549,
    345,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    540,
    919,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    644,
    908,
    anchor="nw",
    text="",
    fill="#ea7f85",
    font=("Default Font", 12 * -1)
)

canvas.create_text(
    5,
    156,
    anchor="nw",
    text="BLUEBERRY SMOOTHIE",
    fill="#000000",
    font=("Kanit", 78 * -1)
)

window.resizable(False, False)
window.mainloop()
